const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={products:[],cat:"All",sort:"featured",cart:JSON.parse(localStorage.getItem("bfeCart")||"[]"),wish:JSON.parse(localStorage.getItem("bfeWish")||"[]")};
const money=n=>"Rp"+Number(n).toLocaleString("id-ID"); const save=()=>{localStorage.setItem("bfeCart",JSON.stringify(state.cart));localStorage.setItem("bfeWish",JSON.stringify(state.wish))};
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2200)}
async function init(){state.products=await fetch("products.json").then(r=>r.json());render();renderCart();renderWish();bind()}
function list(){let a=state.products.filter(p=>state.cat==="All"||p.category===state.cat);if(state.sort==="low")a.sort((a,b)=>a.price-b.price);if(state.sort==="high")a.sort((a,b)=>b.price-a.price);if(state.sort==="rating")a.sort((a,b)=>b.rating-a.rating);return a}
function render(){$("#grid").innerHTML=list().map(p=>`<article class="card"><div class="photo"><img loading="lazy" src="${p.image}" alt="${p.name}"><span class="badge">${p.badge}</span><button class="heart" onclick="wish(${p.id})">${state.wish.includes(p.id)?"♥":"♡"}</button></div><div class="info"><div class="meta"><span>${p.category}</span><span>★ ${p.rating}</span></div><h3>${p.name}</h3><div class="price">${p.price?money(p.price):"STYLE GUIDE"}</div><div class="cardActions"><button class="small" onclick="detail(${p.id})">DETAIL</button><button class="small dark" onclick="${p.price?`add(${p.id})`:`detail(${p.id})`}">${p.price?"ADD +":"VIEW"}</button></div></div></article>`).join("")}
function add(id){let x=state.cart.find(i=>i.id===id);x?x.qty++:state.cart.push({id,qty:1});save();renderCart();toast("Added to your bag ✦")}
function wish(id){state.wish.includes(id)?state.wish=state.wish.filter(x=>x!==id):state.wish.push(id);save();render();renderWish();toast(state.wish.includes(id)?"Saved to wishlist ♡":"Removed from wishlist")}
function renderCart(){let a=state.cart.map(i=>({...state.products.find(p=>p.id===i.id),qty:i.qty})).filter(Boolean);$("#cartCount").textContent=a.reduce((s,x)=>s+x.qty,0);$("#cartItems").innerHTML=a.length?a.map(p=>`<div class="drawerItem"><img src="${p.image}"><div><h4>${p.name}</h4><p>${money(p.price)}</p><div class="qty"><button onclick="qty(${p.id},-1)">−</button><span>${p.qty}</span><button onclick="qty(${p.id},1)">+</button></div></div><button class="remove" onclick="remove(${p.id})">×</button></div>`).join(""):`<div class="empty">Your bag is waiting for its first favorite ✦</div>`;$("#total").textContent=money(a.reduce((s,p)=>s+p.price*p.qty,0))}
function qty(id,n){let x=state.cart.find(i=>i.id===id);x.qty+=n;if(x.qty<1)state.cart=state.cart.filter(i=>i.id!==id);save();renderCart()}
function remove(id){state.cart=state.cart.filter(i=>i.id!==id);save();renderCart()}
function renderWish(){let a=state.products.filter(p=>state.wish.includes(p.id));$("#wishCount").textContent=a.length;$("#wishItems").innerHTML=a.length?a.map(p=>`<div class="drawerItem"><img src="${p.image}"><div><h4>${p.name}</h4><p>${p.price?money(p.price):p.category}</p><button class="small" onclick="detail(${p.id})">VIEW</button></div><button class="remove" onclick="wish(${p.id})">×</button></div>`).join(""):`<div class="empty">Belum ada wishlist ♡</div>`}
function detail(id){let p=state.products.find(x=>x.id===id);$("#modalContent").innerHTML=`<div class="modalProduct"><img src="${p.image}" alt="${p.name}"><div><p class="eyebrow">${p.badge} · ${p.category}</p><h2>${p.name}</h2><p>★ ${p.rating} / 5</p><h3>${p.price?money(p.price):"STYLE INSPIRATION"}</h3><p style="line-height:1.8;color:#596076">${p.description}</p>${p.price?`<button class="primary" onclick="add(${p.id})">ADD TO BAG →</button>`:""}</div></div>`;$("#modal").classList.add("show")}
function drawer(id){$("#overlay").classList.add("show");$("#"+id).classList.add("show")}
function closeAll(){$("#overlay").classList.remove("show");$$(".drawer").forEach(x=>x.classList.remove("show"));$("#modal").classList.remove("show");$("#searchPage").classList.remove("show")}
function search(q){let a=state.products.filter(p=>(p.name+p.category).toLowerCase().includes(q.toLowerCase()));$("#results").innerHTML=a.map(p=>`<div class="result" onclick="detail(${p.id});$('#searchPage').classList.remove('show')"><img src="${p.image}"><div><b>${p.name}</b><p>${p.category}</p></div></div>`).join("")}
function bind(){$$("#chips .chip").forEach(b=>b.onclick=()=>{state.cat=b.dataset.category;$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});$("#sort").onchange=e=>{state.sort=e.target.value;render()};$("#cartBtn").onclick=()=>drawer("cartDrawer");$("#wishBtn").onclick=()=>drawer("wishDrawer");$("#overlay").onclick=closeAll;$$(".drawer .close").forEach(x=>x.onclick=closeAll);$("#searchBtn").onclick=()=>{$("#searchPage").classList.add("show");$("#searchInput").focus()};$(".searchClose").onclick=closeAll;$(".modalClose").onclick=closeAll;$("#searchInput").oninput=e=>search(e.target.value);$("#menuBtn").onclick=()=>$("#nav").classList.toggle("show");$("#allBtn").onclick=()=>{state.cat="All";$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.category==="All"));render()};$("#inspireBtn").onclick=()=>{state.cat="Modest";$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.category==="Modest"));render();$("#shop").scrollIntoView({behavior:"smooth"})};$("#newsletter").onsubmit=e=>{e.preventDefault();toast("Welcome to BFÉ Insiders! ✦");e.target.reset()};$("#checkout").onclick=()=>toast("Demo checkout — siap dihubungkan ke payment gateway!");$("#langBtn").onclick=()=>{let b=$("#langBtn");b.textContent=b.textContent==="ID"?"EN":"ID";toast(b.textContent==="EN"?"English mode preview":"Mode Bahasa Indonesia")};window.addEventListener("scroll",()=>$("#topBtn").classList.toggle("show",scrollY>500));$("#topBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"})}
window.add=add;window.wish=wish;window.qty=qty;window.remove=remove;window.detail=detail;init();